Parameters:
  VpcId:
    Type: String
    Description: The ID of the Amazon Virtual Private Cloud (VPC) that Studio uses for communication.
  Subnets:
    Type: String
    Description: The comma separated list of VPC subnet IDs that Studio uses for communication.


Resources:
  
  # Needs to be attached to the Studio Admin user
  CreateSageMakerStudioUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CreateSageMakerStudioUserPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: CreateSageMakerStudioUserPolicy
            Effect: Allow
            Action:
              - sagemaker:CreateUserProfile
            Resource: "*"
            Condition:
              ForAnyValue:StringEquals:
                aws:TagKeys:
                  - studiouserid

  # to be attached to Studio Users. Enforces that users can open studio which belongs to them
  CreatePresignedDomainUrlPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CreatePresignedDomainUrlPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: CreatePresignedDomainUrlPolicy
            Effect: Allow
            Action:
              - sagemaker:CreatePresignedDomainUrl
            Resource: "*"
            Condition:
              StringEquals:
                sagemaker:ResourceTag/studiouserid: "${aws:username}"

  SageMakerReadOnlyAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SageMakerReadOnlyAccessPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AmazonSageMakerDescribeReadyOnlyPolicy
            Effect: Allow
            Action:
              - sagemaker:Describe*
              - sagemaker:GetSearchSuggestions
            Resource: "*"
          - Sid: AmazonSageMakerListOnlyPolicy
            Effect: Allow
            Action:
              - sagemaker:List*
            Resource: "*"            
          - Sid: AmazonSageMakerUIandMetricsOnlyPolicy
            Effect: Allow
            Action:
              - sagemaker:*App
              - sagemaker:Search
              - sagemaker:RenderUiTemplate
              - sagemaker:BatchGetMetrics
            Resource: "*"
          - Sid: AmazonSageMakerEC2ReadOnlyPolicy
            Effect: Allow
            Action:
              - ec2:DescribeDhcpOptions
              - ec2:DescribeNetworkInterfaces
              - ec2:DescribeRouteTables
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSubnets
              - ec2:DescribeVpcEndpoints
              - ec2:DescribeVpcs
            Resource: "*"
          - Sid: AmazonSageMakerIAMReadOnlyPolicy
            Effect: Allow
            Action:
              - iam:ListRoles
            Resource: "*"

  SageMakerAccessSupportingServicesPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SageMakerAccessSupportingServicesPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AmazonSageMakerCRUDAccessS3Policy
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:AbortMultipartUpload
              - s3:DeleteObject
              - s3:CreateBucket
              - s3:ListBucket
              - s3:PutBucketCORS
              - s3:ListAllMyBuckets
              - s3:GetBucketCORS
              - s3:GetBucketLocation
            Resource: "*"

  SageMakerTrainingJobExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SageMakerTrainingJobExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: SageMakerTrainingJobPolicy
          PolicyDocument:            
            Version: "2012-10-17"
            Statement:
              - Sid: SageMakerTraingingJobExecutionPolicy
                Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                  - logs:DescribeLogStreams
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"        

  SageMakerDeveloperPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SageMakerDeveloperPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: SageMakerStudioCreateApp
            Effect: Allow
            Action:
              - sagemaker:CreateApp
            Resource: "*"
          - Sid: AmazonSageMakerStudioIAMPassRole
            Effect: Allow
            Action:
              - iam:PassRole
            Resource: !GetAtt SageMakerTrainingJobExecutionRole.Arn
            Condition:
              StringEquals:
                iam:PassedToService: sagemaker.amazonaws.com
          - Sid: SageMakerInvokeEndpointRole
            Effect: Allow
            Action:
              - sagemaker:InvokeEndpoint
            Resource: "*"
          - Sid: AmazonSageMakerAddTags
            Effect: Allow
            Action:
              - sagemaker:AddTags
            Resource: "*"
          - Sid: AmazonSageMakerCreate
            Effect: Allow
            Action:
              - sagemaker:Create*
            Condition:
              ForAnyValue:StringEquals:
                aws:TagKeys:
                  - team
              StringEqualsIfExists:
                aws:RequestTag/team: "${aws:PrincipalTag/team}"
            Resource: "*"
          - Sid: AmazonSageMakerUpdateDeleteExecutePolicy
            Effect: Allow
            Action:
              - sagemaker:Delete*
              - sagemaker:Stop*
              - sagemaker:Update*
              - sagemaker:Start*
              - sagemaker:DisassociateTrialComponent
              - sagemaker:AssociateTrialComponent
              - sagemaker:BatchPutMetrics
            Resource: "*"
            Condition:
              StringEquals:
                aws:PrincipalTag/team: "${sagemaker:ResourceTag/team}"

  SageMakerTeamExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SageMakerTeamExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref SageMakerReadOnlyAccessPolicy
        - !Ref SageMakerAccessSupportingServicesPolicy
        - !Ref SageMakerDeveloperPolicy
      Tags:
        - Key: team
          Value: StudioTeam

  SageMakerDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      DomainName: SageMaker-Domain
      VpcId: !Ref VpcId
      SubnetIds: !Split [',', !Ref Subnets ]      
      AuthMode: IAM
      DefaultUserSettings:
        ExecutionRole: !GetAtt SageMakerTeamExecutionRole.Arn
